source 'https://github.com/CocoaPods/Specs.git'
use_frameworks!

target 'MomentsModels_Example', :exclusive => true do
  pod "MomentsModels", :path => "../"
end

target 'MomentsModels_Tests', :exclusive => true do
  pod "MomentsModels", :path => "../"
end
